# 网关服务配置

server:
  port: 8080

spring:
  cloud:
    gateway:
      # 全局CORS配置
      globalcors:
        cors-configurations:
          '[/**]':
            # 使用allowedOriginPatterns代替allowed-origins以支持credentials
            allowed-origin-patterns: "*"
            allowed-methods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowed-headers: "*"
            allow-credentials: true
            max-age: 3600

      # 路由配置
      routes:
        # ===== 用户服务相关路由 =====

        # 认证服务路由 (注册、登录)
        - id: auth-service
          uri: lb://user-service
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=1

        # 用户管理路由 (CRUD)
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**
          filters:
            - StripPrefix=1

        # 配置查询路由
        - id: config-service
          uri: lb://user-service
          predicates:
            - Path=/api/config/**
          filters:
            - StripPrefix=1

        # ===== 商品服务路由 =====
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/api/product/**
          filters:
            - StripPrefix=1

        # ===== 订单服务路由 =====
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/api/order/**
          filters:
            - StripPrefix=1

        # ===== 评论服务路由 =====
        - id: comment-service
          uri: lb://comment-service
          predicates:
            - Path=/api/comment/**
          filters:
            - StripPrefix=1

      # 默认过滤器
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials

      # 服务发现配置
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

# JWT配置
jwt:
  # JWT密钥（至少64字节，用于HS512算法）
  secret: Nqpdqkh6se8xtRYwLNjcEvopb1CtTwRN0DxvR0lrGGIiNCoTbKa91g9vbQE+pg4fwqd17I9MLq7rLKP4D5MSVg==
  # Token有效期（毫秒），7天
  expiration: 604800000
  # 白名单（不需要认证的路径）
  whitelist:
    # 认证相关
    - /api/auth/register
    - /api/auth/login
    - /api/auth/test

    # 配置相关
    - /api/config/**

    # 商品相关(无需认证)
    - /api/product              # GET 列表
    - /api/product/*            # GET 详情 (例如: /api/product/1)
    - /api/product/status/*     # GET 按状态查询
    - /api/product/seller/*     # GET 按卖家查询
    - /api/product/category/*   # GET 按分类查询
    - /api/product/search       # GET 搜索


# 日志配置
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    com.zjgsu.lll.secondhand: DEBUG
    org.springframework.web: INFO