# 订单服务配置

server:
  port: 8083

spring:
  # 数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://secondhand-mysql:3306/order_db?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: lilili2004
    hikari:
      maximum-pool-size: 15
      minimum-idle: 5

  # JPA配置
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

# 订单服务特定配置
order-service:
  timeout:
    order-expiry: 1800  # 订单超时时间（秒）
    payment-expiry: 300  # 支付超时时间（秒）
  retry:
    max-attempts: 3
    backoff-delay: 1000

# Resilience4j配置
resilience4j:
  circuitbreaker:
    instances:
      productService:
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10000
        sliding-window-size: 10
        minimum-number-of-calls: 5

logging:
  level:
    com.zjgsu.lll.secondhand: DEBUG
